# Generated by Django 5.1.2 on 2024-10-20 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("porteiros", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitantes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=255, verbose_name="Nome completo"),
                ),
                ("cpf", models.CharField(max_length=11, verbose_name="CPF")),
                (
                    "data_nascimento",
                    models.DateField(verbose_name="Data de nascimento"),
                ),
                (
                    "numero_casa",
                    models.PositiveSmallIntegerField(
                        verbose_name="Número da casa a ser visitada"
                    ),
                ),
                (
                    "placa_veiculo",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        null=True,
                        verbose_name="Placa do veículo",
                    ),
                ),
                (
                    "horario_chegada",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Horário de chegada na portaria"
                    ),
                ),
                (
                    "horario_saida",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Horário de saída do condomínio",
                    ),
                ),
                (
                    "horario_autorizacao",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Horário de autorização de entrada",
                    ),
                ),
                (
                    "morador_resposavel",
                    models.CharField(
                        blank=True,
                        max_length=194,
                        null=True,
                        verbose_name="Nome do morador que autorizou entrada",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="porteiros.porteiro",
                        verbose_name="Porteiro responsável pelo registro",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visitante",
                "verbose_name_plural": "Visitantes",
                "db_table": "Visitante",
            },
        ),
    ]
