# Generated by Django 5.1.2 on 2024-10-22 00:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("visitantes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="Visitantes",
            table="visitante",
        ),
    ]
