# Generated by Django 5.1.2 on 2024-10-22 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0002_alter_visitors_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitantes',
            old_name='morador_resposavel',
            new_name='morador_responsavel',
        ),
        migrations.RemoveField(
            model_name='visitantes',
            name='user',
        ),
    ]
